### ISSUE TITLE
接雨水

### ISSUE THREAD

**Issue by zxh991103** [lwshanbd/leetcode-baodi#1]
来个接雨水！

**Comment by lwshanbd** [comment]
我花了一个小时写过了，但只超越了5%的人，让我来优化一下
<img width="857" alt="image" src="https://user-images.githubusercontent.com/43607251/184970808-4e6a04fd-ea9a-4090-80f1-fc254039df3e.png">

**Comment by lwshanbd** [comment]
擦我发现我写的复杂度是n! + 优化....
我实在是太菜了
